version: '3.8'

services:
  consul:
    build:
      context: ./consul
      dockerfile: Dockerfile
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    networks:
      - internal

  server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - CONSUL_HTTP_ADDR=consul:8500
      - FILE_SERVER_PORT=:8080
      - HTTP_PORT=:8081
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    depends_on:
      - consul
    networks:
      - internal
    ports:
      - "8081"  # Expose the HTTP server port

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - consul
      - server
    networks:
      - internal
      - public

networks:
  internal:
  public: